import { ArrowUpRight, Sparkles } from "lucide-react";

export function Newsletter({ email, setEmail, subscribed, onSubscribe }: { email:string; setEmail:(value:string)=>void; subscribed:boolean; onSubscribe:()=>void }) {
  return <section className="mx-auto max-w-[1220px] px-[5vw] pb-20"><div className="relative overflow-hidden bg-coral px-7 py-10 text-white sm:px-12 sm:py-14"><div className="absolute -right-16 -top-24 h-72 w-72 rounded-full border border-white/20" /><div className="absolute -right-5 -top-14 h-52 w-52 rounded-full border border-white/20" /><div className="relative grid gap-8 lg:grid-cols-[1fr_1.1fr] lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[1.3px] text-white/70">The near letter</p><h2 className="mt-4 max-w-md text-3xl font-bold leading-tight tracking-[-1.5px] sm:text-4xl">A few good things,<br /><span className="font-serif font-normal">once a week.</span></h2></div><div><p className="mb-4 max-w-md text-sm leading-6 text-white/80">New openings, small discoveries, and plans worth making — delivered without the noise.</p>{subscribed ? <div className="border border-white/40 bg-white/10 px-4 py-3 text-sm">You’re on the list. See you in your inbox.</div> : <form onSubmit={event => { event.preventDefault(); onSubscribe(); }} className="flex max-w-lg border border-white/40 bg-white/10 p-1 backdrop-blur-sm"><input value={email} onChange={event => setEmail(event.target.value)} type="email" required placeholder="Your email address" className="min-w-0 flex-1 bg-transparent px-3 text-sm text-white outline-none placeholder:text-white/60" /><button className="bg-white px-4 py-3 text-[11px] font-extrabold text-coral">Subscribe</button></form>}</div></div></div></section>;
}

export function Footer({ onNavigate }: { onNavigate:(page:"discover"|"saved"|"about")=>void }) {
  return <footer className="border-t border-[#dce0d9] bg-paper px-[5vw] py-12"><div className="mx-auto max-w-[1220px]"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_.7fr_.7fr_.9fr]"><div><button onClick={() => onNavigate("discover")} className="text-2xl font-extrabold tracking-[-1.5px]"><Sparkles className="mr-1 inline text-coral" size={18} fill="currentColor" />near<span className="text-coral">.</span></button><p className="mt-4 max-w-xs text-sm leading-6 text-[#747e78]">A thoughtful guide to the best things happening around your city.</p></div><div><p className="font-mono text-[10px] uppercase tracking-wider text-[#8a948e]">Explore</p><div className="mt-4 grid gap-3 text-sm font-semibold"><button className="text-left hover:text-coral" onClick={() => onNavigate("discover")}>Discover events</button><button className="text-left hover:text-coral" onClick={() => onNavigate("saved")}>Saved plans</button><button className="text-left hover:text-coral" onClick={() => onNavigate("about")}>How it works</button></div></div><div><p className="font-mono text-[10px] uppercase tracking-wider text-[#8a948e]">Cities</p><div className="mt-4 grid gap-3 text-sm text-[#747e78]"><span>Brooklyn</span><span>New York</span><span>Coming soon</span></div></div><div><p className="font-mono text-[10px] uppercase tracking-wider text-[#8a948e]">Follow along</p><div className="mt-4 flex gap-3 text-sm font-semibold"><span>Instagram</span><span>Are.na</span></div></div></div><div className="mt-12 flex flex-col justify-between gap-3 border-t border-[#dce0d9] pt-5 text-[10px] text-[#8a948e] sm:flex-row"><span>© 2026 Near, Inc.</span><span>Made for plans worth leaving home for.</span></div></div></footer>;
}
